//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyXeMay_HoangDung
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietXe
    {
        public int MaCT { get; set; }
        public string MaXe { get; set; }
        public string SoKhung { get; set; }
        public string SoMay { get; set; }
        public Nullable<bool> Active { get; set; }
        public string MaPN { get; set; }
        public string MaPX { get; set; }
    
        public virtual PhieuNhap PhieuNhap { get; set; }
        public virtual PhieuXuat PhieuXuat { get; set; }
        public virtual Xe Xe { get; set; }
    }
}
