//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyXeMay_HoangDung
{
    using System;
    using System.Collections.Generic;
    
    public partial class viewLichSuNhap
    {
        public string MaPN { get; set; }
        public string TenXe { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<double> DonGia { get; set; }
        public Nullable<double> ThanhTien { get; set; }
        public Nullable<System.DateTime> NgayNhap { get; set; }
        public string TenNCC { get; set; }
    }
}
