//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyXeMay_HoangDung
{
    using System;
    using System.Collections.Generic;
    
    public partial class viewLichSuXuat
    {
        public string MaPX { get; set; }
        public string TenKH { get; set; }
        public string TenXe { get; set; }
        public string MauSac { get; set; }
        public string SoKhung { get; set; }
        public string SoMay { get; set; }
        public Nullable<double> DonGia { get; set; }
        public Nullable<System.DateTime> NgayXuat { get; set; }
    }
}
